disabled = false
languageCode = "fr"
languageName = "Francais"
weight = 1
title = "Portfolio de Thomas ROBERT"

[params]
  displayName = "FR"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Site internet de présentation, "
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Thomas ROBERT"
  email = "tet@example.com"
#  image = "img/blowfish_logo.png"
#  imageQuality = 96
#   headline = "I'm only human"
  bio = "Ingénieur en système d'information et cyber sécruité"
  links = [
#     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
#     { github = "https://github.com/username" },
#     { gitlab = "https://gitlab.com/username" },
    { linkedin = "https://www.linkedin.com/in/thomas-robert-ece/" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { youtube = "https://youtube.com/username" },
  ]
