[ananke]
show_recent_posts = true # show recent posts on the homepage

[ananke.social]
icon_path = "ananke/socials/%s.svg"

[ananke.social.follow]
new_window_icon = false # show a little "opens in new window" icon next to the link
# add networks to this list in your local config to enable them, remove them to disable them.
# networks = [
#   "facebook",
#   "bluesky",
#   "linkedin"
# ]

[ananke.social.share]
icons = true # show icons for each share link
sharetext = true # show the share text
# add networks to this list in your local config to enable them, remove them to disable them.
# networks = [
#   "email",
#   "facebook",
#   "bluesky",
#   "linkedin"
# ]

# social media network setups

[ananke.social.networks.email]
slug = "email"
label = "Email"
profile = false
icon = "envelope" # font awesome free icon name
link = "mailto:"
[ananke.social.networks.email.particles]
body = "permalink"
subject = "title"

[ananke.social.networks.github]
slug = "github"
label = "GitHub"
color = "#6cc644"
profile = "https://github.com/%s/"
icon = "github" # font awesome brand icon name

[ananke.social.networks.gitlab]
slug = "gitlab"
label = "GitLab"
color = "#FC6D26"
profile = "https://gitlab.com/%s/"
icon = "gitlab" # font awesome brand icon name

[ananke.social.networks.linkedin]
slug = "linkedin"
label = "LinkedIn"
color = "#0077b5"
profile = "http://linkedin.com/in/%s"
icon = "linkedin" # font awesome brand icon name
link = "https://www.linkedin.com/shareArticle"
[ananke.social.networks.linkedin.particles]
url = "permalink"
title = "title"
summary = "description"
source = "permalink"
params = "mini=true"

[ananke.social.networks.stackoverflow]
slug = "stackoverflow"
label = "Stack Overflow"
color = "#f48024"
profile = "https://stackoverflow.com/users/%s"
icon = "stack-overflow" # font awesome brand icon name


[ananke.social.networks.tiktok]
slug = "tiktok"
label = "TikTok"
color = "#fe2c55"
profile = "https://www.tiktok.com/@%s"
icon = "tiktok" # font awesome brand icon name



